services:
  mysql-exam:
    container_name: mysql-exam
    image: mysql:8
    ports:
      - "63306:3306"
    networks:
      - my-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: examListeCourses
  
  php-apache:
    container_name: php-apache
    image: damienpm/php-apache-mysqli
    ports:
      - "8080:80"
    networks:
      - my-net
    volumes:
      - .\:/var/www/html

networks:
  my-net: {}